import type { Metadata} from 'next'
import Link from 'next/link';
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import SideNav from '../components/sidenav';'@/app/ui/dashboard/sidenav.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {
      }
      <head />
      <body>
        <div className="flex flex-row h-screen">
          <div className="flex flex-row md:flex-row md:overflow-hidden">
            <div className="w-full flex-none md:w-64">
              <SideNav />
            </div>
          </div>
          <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
        </div>  

      </body>
    </html>
  )
}
